### PR TITLE
fix: add Sync() calls to persist filesystem changes to storage 

### LINKED ISSUE #9: tinyfs issues on Adafruit Gran Central M4 board
I'm testing the tinyfs on an [Adafruit Gran Central M4 board](https://www.adafruit.com/product/4064), but the changes are not stored on the SPI Flash device.

I'm using the QSPI example

Device is detected JEDEC ID: C84017, and the default file systems works properly
```
==> ls
drwxrwxrwx     0 .fseventsd
-rwxrwxrwx     0 .metadata_never_index
-rwxrwxrwx     0 .Trashes
-rwxrwxrwx   102 boot_out.txt
```
but "samples", mkdir, create does not create the expected items.

format works removing all the default files

All the details are attached on the console capture [tiosync-20221016T181113.txt](https://github.com/tinygo-org/tinyfs/files/9795599/tiosync-20221016T181113.txt)

### PR DESCRIPTION
**Pull request by marcelfarres**
I was trying to create folders & files in the SD card and it was not working. 

This changes seem to make it functional again. 

I test it on a M4 Gran Central, and seems to have dir persistent and creation even after mounting/un-moutning the file system. 

Not an expert in any extend on TinyGo, hope it helps/you can test it/review it. 

- Add Sync() after Format, Unmount, Remove, Rename, Mkdir
- Add Sync() after File.Close, File.Sync, File.Truncate
- Sync on OpenFile with O_CREATE/O_TRUNC flags
- Fix cache invalidation in lfs_bd_flush
- Add TestDirectoryPersistence and NestedDirectories tests"

 Should fix #9

### CODE REVIEW

**Comment by marcelfarres** [comment]
# Fix filesystem persistence on SD cards

## Problem

I was working with LittleFS on a Grand Central M4 with an SD card and noticed that directories and files I created weren't surviving a power cycle. I'd run `mkdir`, it would succeed, `ls` would show the directory. But after unplugging and reconnecting (or even just unmounting and remounting), everything was gone.

## Investigation

I traced the data flow through the code:

1. When I call `fs.Mkdir("test")`, it goes to [`go_lfs.go:247`](https://github.com/tinygo-org/tinyfs/pull/27/files#diff-4c9e8e51e9f0e1b4e0d3e0f0e1e0e1e0R247)
2. That calls the C library's `lfs_mkdir()` via CGo
3. LittleFS writes through the callbacks in `go_lfs_callbacks.go` to the SD card driver
4. The SD card driver buffers the writes... and that's where they stay

The problem: the SD card driver holds writes in a buffer for efficiency. Without explicitly calling `Sync()`, that buffer never gets flushed to the physical flash. On power loss, the buffered data is gone.

Looking at the original code, I noticed that mutating operations just returned after calling the C function—no sync. The block device interface in `tinyfs.go` defines a `Syncer` interface, but it wasn't being used after filesystem operations.

## What I changed

### `littlefs/go_lfs.go`

Added `Sync()` calls after every operation that modifies the filesystem. Example for `Mkdir`:

```go
func (l *LFS) Mkdir(path string, _ os.FileMode) error {
    cs := (*C.char)(cstring(path))
    defer C.free(unsafe.Pointer(cs))
    if err := errval(C.lfs_mkdir(l.lfs, cs)); err != nil {
        return err
    }
    if syncer, ok := l.dev.(tinyfs.Syncer); ok {
        return syncer.Sync()  // <-- This was missing!
    }
    return nil
}
```

Same pattern applied to:

- `Format()` - sync after formatting
- `Unmount()` - sync before closing  
- `Remove()` - sync after deletion
- `Rename()` - sync after rename
- `OpenFile()` with O_CREATE/O_TRUNC - sync after creating
- `File.Close()` - sync after closing
- `File.Sync()` - sync to block device
- `File.Truncate()` - sync after truncation

### `littlefs/go_lfs_test.go`

Added tests:

- `TestDirectoryPersistence` - creates a directory, unmounts, remounts, verifies it persists
- `NestedDirectories` - creates 3 levels of nested directories

## Testing

Tested on actual hardware (Grand Central M4 + SD card):

- Formatted the card
- Created nested directories (`level1/level2/level3`)  
- Created files
- Unmounted and remounted
- Everything persisted ✓

File: littlefs/go_lfs.go [hunk 1]
```diff
@@ -261,6 +291,24 @@ func (l *LFS) OpenFile(path string, flags int) (tinyfs.File, error) {
 		return nil, err
 	}
 
+	if flags&(os.O_CREATE|os.O_TRUNC) != 0 {
```
Comment (deadprogram) [inline littlefs/go_lfs.go]: I do not think it makes sense to call `Sync()` on an `Open()`.

File: littlefs/go_lfs.go [hunk 2]
```diff
@@ -373,12 +428,27 @@ func (f *File) Stat() (os.FileInfo, error) {
 
 // Sync synchronizes to storage so that any pending writes are written out.
 func (f *File) Sync() error {
-	return errval(C.lfs_file_sync(f.lfs.lfs, f.fileptr()))
+	if err := errval(C.lfs_file_sync(f.lfs.lfs, f.fileptr())); err != nil {
+		return err
+	}
+	if syncer, ok := f.lfs.dev.(tinyfs.Syncer); ok {
```
Comment (deadprogram) [inline littlefs/go_lfs.go]: Actually `Sync()` on a `Sync()`? Seems like a yes! :+1:

**Comment by deadprogram** [comment]
Hello @marcelfarres thanks for the code submission. Please see my comments.

**Comment by deadprogram** [comment]
I probably did not notice the issue due to using flash pretty much all of the time.

**Comment by marcelfarres** [comment]
I am still investigating the fix, somehow I can not reproduce the error or the fix all the time? 

Also it seems that using different -opt levels influence the results (with the unpatch branch opt 0 1 2 have the bug, but s and z pass the tests). Any idea or experience on that? 

I want to be sure that the change does not add to the unreliable behavior.

It also seems that SPI freq plays a role too? 

A bit puzzle.

**Comment by marcelfarres** [comment]
Hey @deadprogram, this turned into a completely different fix than what I originally pushed.

Long story short: the mkdir bug has nothing to do with Sync(). It's LLVM generating bad code for one specific function (`lfs_dir_fetchmatch`) when you build at `-opt=2`. At `-opt=z` the bug never appears, which is why the Sync calls looked like they helped — they didn't, I just wasn't hitting the right opt level.

I spent a while trying to find a targeted workaround (volatile vars, memory barriers, noinline, etc.) but nothing short of disabling optimization on that one function works. So the fix is a single `__attribute__((optnone))` on `lfs_dir_fetchmatch`.

While I was at it I also:

- Reverted all the Sync()/cache changes (they were a red herring)
- Fixed a type mismatch in the CGo callbacks (`size` was `int` but needs to be `uint32` to match C — was crashing unit tests on 64-bit)
- Added some directory tests and an SD card example you can flash to verify

Tested on Grand Central M4 + SD at `-opt=2`: 50/50 mkdir+stat cycles pass, nested dirs work, files in subdirs work. Without the fix, everything fails.


PD: Sorry for the random co-pilot spam.

**Comment by deadprogram** [comment]
Took a bit to digest the changes here, @marcelfarres but totally makes sense. Thanks for working on this! Now merging.
